"""Build the delivery ZIP from the working tree.

    python scripts/package.py

`git archive` must NOT be used here, and this is why the previous package went
stale: parts of the tree are untracked, and `data/` + `AI Engineer/` are
deliberately gitignored yet have to ship or the evaluator cannot run
`ingest.py` or open the Part 2 notebook. So we walk the tree and exclude
explicitly — an allow-by-default, deny-by-list policy.

Verify a fresh package by extracting it somewhere clean and running the tests
from there; a file listing does not prove the corpus is usable.
"""

import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "rag-demo.zip"

# Directories skipped wherever they appear.
SKIP_DIRS = {
    "__pycache__",
    ".git",
    ".venv",
    ".claude",
    ".pytest_cache",
    ".ruff_cache",
    ".ipynb_checkpoints",
    "node_modules",  # reinstalled by run_web.py / Docker
    ".next",  # build output
    ".turbo",
    "storage",  # regenerated by ingest.py
    "figures",  # regenerated by the notebook
    "htmlcov",
    ".mypy_cache",
}

# Paths relative to ROOT that are skipped entirely.
SKIP_PATHS = {
    Path("rag-demo.zip"),
    Path(".env"),  # real secrets; .env.example ships instead
    Path(".coverage"),
    Path("web/tsconfig.tsbuildinfo"),
    Path("web/next-env.d.ts"),  # regenerated by next
    # Agent tooling, not deliverables. web/AGENTS.md is regenerated by `next dev`.
    Path("CLAUDE.md"),
    Path("web/CLAUDE.md"),
    Path("web/AGENTS.md"),
}

SKIP_SUFFIXES = {".pyc", ".pyo", ".log"}


def should_skip(rel: Path) -> bool:
    if rel in SKIP_PATHS:
        return True
    if rel.suffix in SKIP_SUFFIXES:
        return True
    return any(part in SKIP_DIRS for part in rel.parts)


def main() -> int:
    sys.stdout.reconfigure(encoding="utf-8")
    if OUT.exists():
        OUT.unlink()

    written = 0
    total_bytes = 0
    with zipfile.ZipFile(OUT, "w", zipfile.ZIP_DEFLATED, compresslevel=9) as zf:
        for path in sorted(ROOT.rglob("*")):
            if not path.is_file():
                continue
            rel = path.relative_to(ROOT)
            if should_skip(rel):
                continue
            zf.write(path, rel.as_posix())
            written += 1
            total_bytes += path.stat().st_size

    print(f"{written} dosya yazildi")
    print(f"kaynak toplam : {total_bytes / 1_048_576:.1f} MB")
    print(f"zip boyutu    : {OUT.stat().st_size / 1_048_576:.1f} MB")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
